sudo: false

env:
  global:
    - VIPS_VERSION_MAJOR=8
    - VIPS_VERSION_MINOR=6
    - VIPS_VERSION_MICRO=4
    - PATH=$HOME/vips/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH

dist: trusty

addons:
  apt:
    packages:
      - libexpat1-dev
      - gettext
      - libglib2.0-dev
      - liborc-0.4-dev
      - libfftw3-dev
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libgif-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev
cache:
  directories:
    - $HOME/vips

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"

# some strange package versioning issue with pypy?
matrix:
  allow_failures:
    - python: nightly

install:
  - pip install -U .[test]

script:
  - python setup.py test

# the vips7 py binding won't work with pypy, make sure it's off
before_install:
  - uname -a
  - bash install-vips.sh --without-python
  - pip install -U setuptools
