[build-system]
requires = [
    # First version of setuptools to support pyproject.toml configuration
    "setuptools>=61.0.0",
    "wheel",
    # Must be kept in sync with `project.dependencies`
    "cffi>=1.0.0",
    "pkgconfig>=1.5",
]
build-backend = "setuptools.build_meta"

[project]
name = "pyvips"
authors = [
    {name = "John Cupitt", email = "jcupitt@gmail.com"},
]
description = "binding for the libvips image processing library"
readme = "README.rst"
keywords = [
    "image processing",
]
license = {text = "MIT"}
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Multimedia :: Graphics :: Graphics Conversion",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    # Must be kept in sync with `build-system.requires`
    "cffi>=1.0.0",
]
dynamic = [
    "version",
]

[project.urls]
changelog = "https://github.com/libvips/pyvips/blob/master/CHANGELOG.rst"
documentation = "https://libvips.github.io/pyvips/"
funding = "https://opencollective.com/libvips"
homepage = "https://github.com/libvips/pyvips"
issues = "https://github.com/libvips/pyvips/issues"
source = "https://github.com/libvips/pyvips"

[tool.setuptools]
# We try to compile as part of install, so we can't run in a ZIP
zip-safe = false
include-package-data = false

[tool.setuptools.dynamic]
version = {attr = "pyvips.version.__version__"}

[tool.setuptools.packages.find]
exclude = [
    "doc*",
    "examples*",
    "tests*",
]

[tool.cibuildwheel]
# Only build CPython 3.7, because we have portable abi3 wheels
# Apple Silicon is only available on 3.8 and later
build = [
    "cp37-*",
    "cp38-macosx_arm64"
]
build-frontend = "build"
before-build = "bash {project}/cibw_before_build.sh"
test-command = "python -c \"import pyvips; assert pyvips.API_mode\""
environment-pass = ["RUNNER_OS"]

[tool.cibuildwheel.environment]
PKG_CONFIG_PATH = "./tmp/lib/pkgconfig"
LD_LIBRARY_PATH = "$(pwd)/tmp/lib"
DYLD_LIBRARY_PATH = "$(pwd)/tmp/lib"
MACOSX_DEPLOYMENT_TARGET = "10.13"

[tool.cibuildwheel.linux]
archs = "x86_64 aarch64"
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
musllinux-x86_64-image = "musllinux_1_2"
musllinux-aarch64-image = "musllinux_1_2"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
# Exclude a couple of system libraries from grafting into the resulting wheel
repair-wheel-command = """\
auditwheel repair -w {dest_dir} {wheel} \
--exclude libc.so --exclude libstdc++.so.6 --exclude libgcc_s.so.1\
"""

[tool.cibuildwheel.macos]
archs = "x86_64 arm64"
# Apple Silicon CI runners are not widely available
test-skip = "*-macosx_arm64"

[tool.cibuildwheel.windows]
archs = "AMD64 x86"
# Use delvewheel on windows
before-all = "pip install delvewheel"
repair-wheel-command = "delvewheel repair --add-path ./tmp/lib -w {dest_dir} {wheel}"

[project.optional-dependencies]
# All the following are used for our own testing
tox = ["tox"]
test = [
    "pytest",
    "pyperf",
]
sdist = ["build"]
doc = [
    "sphinx",
    "sphinx_rtd_theme",
]

[tool.pytest.ini_options]
norecursedirs = ["tests/helpers"]
